### ISSUE TITLE
Integrate a LYSO description in ldmx-sw geometry and simulations

### ISSUE THREAD

**Issue by bryngemark** [LDMXAnalysis/ldmx-sw#1225]
**Is your feature request related to a problem? Please describe.**
@joyang8caltech has been making standalone Geant4 simulations of a LYSO target geometry, but this won't tell us how a LYSO target would perform in LDMX. We need to pull it into our framework to make studies to scale and with simulations of different types of processes. 

**Describe the solution you'd like**
The concrete steps needed are
 - [x] import standalone G4 geometry (from James) into ldmx-sw (see issue https://github.com/LDMX-Software/ldmx-sw/issues/1283 for the 8 GeV version of this)
 - [x] ensure and validate that we can read it out like a TS module #1741
 - [x] set up a procedure for running MadGraph+G4DarkBrem signal generation with LYSO (compound material of other elements than we usually use) (see issue https://github.com/LDMX-Software/ldmx-sw/issues/1228)
 - [x] implement a Birks' law correction for LYSO (see issue #1088) 

Consider this a tracking issue. I will make/link to issues for each of these steps. 

**Describe alternatives you've considered**
 N/A

**Additional context**
Any work in this direction by anyone is welcome. Come to the TS and/or sw dev meetings for help and to showcase your work!
