### ISSUE TITLE
Updates to the Hcal reconstrucion

### ISSUE THREAD

**Issue by cmantill** [LDMXAnalysis/ldmx-sw#1347]
## Goals

- [ ] Update waveform (pulse)
- [ ] Update amplitude correction (Ampl[t-1]/Ampl[t])
- [ ] Update TOA timewalk correction
- [x] Add TOT reconstruction
- [x] LDMX-Software/Hcal#42
- [x] Make sure that all digis are processed. Currently the code assumes that digis are ordered. See issue [1067](https://github.com/LDMX-Software/ldmx-sw/issues/1067).
- [x] Modify the position measurement for measurements carried out w the horizontal bars shifted. See issue [37](https://github.com/LDMX-Software/Hcal/issues/37).

**Comment by tomeichlersmith** [comment]
Working on add TOT recon with LDMX-Software/Hcal#44
